### ISSUE TITLE
 [Errno 2] No such file or directory: './data/COCO/annotations/instances_valminusminival2014.json'

### ISSUE THREAD

**Issue by Zyt-wenwne** [Ze-Yang/Context-Transformer#13]
I run the python data/split_coco_dataset_voc_nonvoc.py ，and I get this problem, how can I solve it.

Split 1: 346721 anns; save to ./data/COCO/annotations/split_voc_instances_train2014.json
Split 2: 258186 anns; save to ./data/COCO/annotations/split_nonvoc_instances_train2014.json
processing dataset ./data/COCO/annotations/instances_valminusminival2014.json
Traceback (most recent call last):
  File "data/split_coco_dataset_voc_nonvoc.py", line 87, in <module>
    split_dataset(dataset_prefix + s, voc_inds, split1_prefix + s, split2_prefix + s)
  File "data/split_coco_dataset_voc_nonvoc.py", line 16, in split_dataset
    with open(dataset_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/COCO/annotations/instances_valminusminival2014.json'

**Comment by Ze-Yang** [comment]
You should first download the COCO 2014 dataset [here](https://cocodataset.org/#download), and place them accordingly under the instructions I provide in the README.md file. This error indicates that you did not correctly set up the dataset.

**Comment by Zyt-wenwne** [comment]
thanks for your reply, I have downloaded  the COCO 2014 dataset

**Comment by Zyt-wenwne** [comment]
> You should first download the COCO 2014 dataset [here](https://cocodataset.org/#download), and place them accordingly under the instructions I provide in the README.md file. This error indicates that you did not correctly set up the dataset.

a problem had occured when I run the:
python train.py --save-folder weights/VOC_split1_pretrain -d VOC -p 1 -max 50000 --steps 30000 40000 --checkpoint-period 4000 --warmup-iter 1000 --setting incre --split 1

the code of python train.py --save-folder weights/COCO60_pretrain -d COCO -p 1  had finished


[04/27 08:26:11 Context-Transformer]: Starting training from iteration 0
Traceback (most recent call last):
  File "train.py", line 300, in <module>
    train(model, args.resume)
  File "train.py", line 220, in train
    data, targets = next(data_loader)
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/plc319/桌面/Context-Transformer-master/data/voc0712.py", line 235, in __getitem__
    img1, target1 = self.preproc(img1, target1)
  File "/home/plc319/桌面/Context-Transformer-master/data/data_augment.py", line 178, in __call__
    image_o = image.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by Ze-Yang** [comment]
I have no idea what the problem is with the information you provide. By the way, you may try to avoid using Chinese characters in the directory path since it may sometimes cause some weird errors that are hard to be noticed. Hope it helps. Thanks.

**Comment by alphacyp** [comment]
> 

Has your problem been solved? I have encountered the same problem as you. Can you tell me how you solved it? Thank you!

**Comment by alphacyp** [comment]
> Has your problem been solved? I have encountered the same problem as you. Can you tell me how you solved it? Thank you!

Has your problem been solved? I have encountered the same problem as you. Can you tell me how you solved it? Thank you!

**Comment by alphacyp** [comment]
> > You should first download the COCO 2014 dataset [here](https://cocodataset.org/#download), and place them accordingly under the instructions I provide in the README.md file. This error indicates that you did not correctly set up the dataset.
> 
> a problem had occured when I run the: python train.py --save-folder weights/VOC_split1_pretrain -d VOC -p 1 -max 50000 --steps 30000 40000 --checkpoint-period 4000 --warmup-iter 1000 --setting incre --split 1
> 
> the code of python train.py --save-folder weights/COCO60_pretrain -d COCO -p 1 had finished
> 
> [04/27 08:26:11 Context-Transformer]: Starting training from iteration 0 Traceback (most recent call last): File "train.py", line 300, in train(model, args.resume) File "train.py", line 220, in train data, targets = next(data_loader) File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in **next** data = self._next_data() File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data return self._process_data(data) File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data data.reraise() File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop data = fetcher.fetch(index) File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/plc319/anaconda3/envs/ct/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/plc319/桌面/Context-Transformer-master/data/voc0712.py", line 235, in **getitem** img1, target1 = self.preproc(img1, target1) File "/home/plc319/桌面/Context-Transformer-master/data/data_augment.py", line 178, in **call** image_o = image.copy() AttributeError: 'NoneType' object has no attribute 'copy'

Has your problem been solved? I have encountered the same problem as you. Can you tell me how you solved it? Thank you!
